#include <common.h>

#define MC_STRINGIFY_IMPL(value) #value
#define MC_STRINGIFY(value) MC_STRINGIFY_IMPL(value)
#define MC_GP(field) MC_STRINGIFY(CTR_MEMCARD_GP_##field) "($gp)"

// NOTE(aalhendi): GCC 2.8.1 schedules this state machine differently. Retail
// needs the stage load before its prologue and specific call delay slots.
// The jump table uses symbolic code labels, not copied retail data bytes.
// GP displacements and the icon address are checked against the shared layouts.
__asm__(".section .MEMCARD_HandleEvent,\"ax\",@progbits\n"
        ".align 2\n"
        ".ent\tMEMCARD_HandleEvent\n"
        ".set\tnoreorder\n"
        ".globl MEMCARD_HandleEvent\n"
        "MEMCARD_HandleEvent:\n"
        "lw $v0," MC_GP(STAGE) "\n"
        "addiu $sp,$sp,-24\n"
        "sw $ra,20($sp)\n"
        "addiu $v1,$v0,-1\n"
        "sltiu $v0,$v1,14\n"
        "beqz $v0,.LMemcardDefaultTimeout\n"
        "sw $s0,16($sp)\n"
        "lui $v0,%hi(.LMemcardHandleEventTable)\n"
        "addiu $v0,$v0,%lo(.LMemcardHandleEventTable)\n"
        "sll $v1,$v1,0x2\n"
        "addu $v1,$v1,$v0\n"
        "lw $v0,0($v1)\n"
        "nop\n"
        "jr $v0\n"
        "nop\n"
        ".LMemcardGetInfo:\n"
        "jal MEMCARD_GetNextSwEvent\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "bnez $s0,.LMemcardGetInfoCheckOtherEvent\n"
        "addiu $v0,$zero,3\n"
        "lw $v1," MC_GP(STATUS_FLAGS) "\n"
        "nop\n"
        "andi $v0,$v1,0x1\n"
        "beqz $v0,.LMemcardGetInfoCheckUnformatted\n"
        "addiu $v0,$zero,2\n"
        "sw $v0," MC_GP(STAGE) "\n"
        "jal MEMCARD_SkipEvents\n"
        "addiu $s0,$zero,1\n"
        ".LMemcardGetInfoPollLoad:\n"
        "lw $a0," MC_GP(SLOT) "\n"
        "jal _card_load\n"
        "nop\n"
        "bne $v0,$s0,.LMemcardGetInfoPollLoad\n"
        "nop\n"
        "j .LMemcardReturnSavedEvent\n"
        "addiu $s0,$zero,7\n"
        ".LMemcardGetInfoCheckUnformatted:\n"
        "andi $v0,$v1,0x2\n"
        "bnez $v0,.LMemcardResetStage\n"
        "nop\n"
        "sw $zero," MC_GP(FREE_BYTES) "\n"
        "j .LMemcardResetStage\n"
        "addiu $s0,$zero,5\n"
        ".LMemcardGetInfoCheckOtherEvent:\n"
        "bne $s0,$v0,.LMemcardGetInfoReturnOrReset\n"
        "addiu $v0,$zero,7\n"
        "jal MEMCARD_SkipEvents\n"
        "addiu $s0,$zero,1\n"
        ".LMemcardGetInfoPollClear:\n"
        "lw $a0," MC_GP(SLOT) "\n"
        "jal _card_clear\n"
        "nop\n"
        "bne $v0,$s0,.LMemcardGetInfoPollClear\n"
        "nop\n"
        "jal MEMCARD_WaitForHwEvent\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "bnez $s0,.LMemcardResetStage\n"
        "addiu $v0,$zero,2\n"
        "sw $v0," MC_GP(STAGE) "\n"
        "jal MEMCARD_SkipEvents\n"
        "addiu $s0,$zero,1\n"
        ".LMemcardGetInfoPollReload:\n"
        "lw $a0," MC_GP(SLOT) "\n"
        "jal _card_load\n"
        "nop\n"
        "bne $v0,$s0,.LMemcardGetInfoPollReload\n"
        "nop\n"
        "j .LMemcardReturnSavedEvent\n"
        "addiu $s0,$zero,7\n"
        ".LMemcardGetInfoReturnOrReset:\n"
        "beq $s0,$v0,.LMemcardReturnSavedEvent\n"
        "addu $v0,$s0,$zero\n"
        "sw $zero," MC_GP(STAGE) "\n"
        "sw $zero," MC_GP(FREE_BYTES) "\n"
        "j .LMemcardReturn\n"
        "nop\n"
        ".LMemcardNewCard:\n"
        "jal MEMCARD_GetNextSwEvent\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "bnez $s0,.LMemcardNewCardCheckEvent\n"
        "addiu $v0,$zero,3\n"
        "lw $a0," MC_GP(SLOT) "\n"
        "lw $v0," MC_GP(STATUS_FLAGS) "\n"
        "addiu $v1,$zero,-2\n"
        "sw $zero," MC_GP(STAGE) "\n"
        "ori $v0,$v0,0x2\n"
        "and $v0,$v0,$v1\n"
        "sw $v0," MC_GP(STATUS_FLAGS) "\n"
        "jal MEMCARD_GetFreeBytes\n"
        "addiu $s0,$zero,3\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardNewCardCheckEvent:\n"
        "bne $s0,$v0,.LMemcardNewCardReturnOrReset\n"
        "addiu $v0,$zero,7\n"
        "addiu $s0,$zero,5\n"
        "lw $v0," MC_GP(STATUS_FLAGS) "\n"
        "addiu $v1,$zero,-4\n"
        "sw $zero," MC_GP(STAGE) "\n"
        "and $v0,$v0,$v1\n"
        ".LMemcardStoreStatusReturn:\n"
        "sw $v0," MC_GP(STATUS_FLAGS) "\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardNewCardReturnOrReset:\n"
        "beq $s0,$v0,.LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardResetStage:\n"
        "sw $zero," MC_GP(STAGE) "\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardLoadPart0Start:\n"
        "jal MEMCARD_GetNextSwEvent\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "bnez $s0,.LMemcardLoadStartRetryOrClose\n"
        "addiu $v0,$zero,7\n"
        "lw $v0," MC_GP(BUFFER) "\n"
        "lw $a1," MC_GP(FILE_SIZE) "\n"
        "lbu $a0,2($v0)\n"
        "addiu $v0,$zero,4\n"
        "sw $v0," MC_GP(STAGE) "\n"
        "andi $a0,$a0,0xf\n"
        "addiu $a0,$a0,1\n"
        "sll $a0,$a0,0x7\n"
        "sw $a0," MC_GP(ICON_SIZE) "\n"
        "jal MEMCARD_ReadFile\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "lw $a1," MC_GP(ICON_SIZE) "\n"
        "lw $a0," MC_GP(FILE_SIZE) "\n"
        "lw $v1," MC_GP(BUFFER) "\n"
        "addu $v0,$a1,$a0\n"
        "addiu $v0,$v0,8191\n"
        "lbu $v1,3($v1)\n"
        "sra $v0,$v0,0xd\n"
        "slt $v0,$v0,$v1\n"
        "beqz $v0,.LMemcardLoadMarkNoBackup\n"
        "sll $v0,$a0,0x1\n"
        "addu $v0,$a1,$v0\n"
        "addiu $v0,$v0,8191\n"
        "sra $v0,$v0,0xd\n"
        "slti $v0,$v0,2\n"
        "bnez $v0,.LMemcardLoadMarkNoBackup\n"
        "addiu $v1,$zero,-5\n"
        "lw $v0," MC_GP(STATUS_FLAGS) "\n"
        "j .LMemcardStoreStatusReturn\n"
        "and $v0,$v0,$v1\n"
        ".LMemcardLoadMarkNoBackup:\n"
        "lw $v0," MC_GP(STATUS_FLAGS) "\n"
        "nop\n"
        "ori $v0,$v0,0x4\n"
        "sw $v0," MC_GP(STATUS_FLAGS) "\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardLoadStartRetryOrClose:\n"
        "beq $s0,$v0,.LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        "lw $v0," MC_GP(RETRIES) "\n"
        "nop\n"
        "blez $v0,.LMemcardCloseFileReturn\n"
        "addiu $v0,$v0,-1\n"
        "sw $v0," MC_GP(RETRIES) "\n"
        "addu $a0,$zero,$zero\n"
        "addiu $a1,$zero,128\n"
        ".LMemcardReadFileReturn:\n"
        "jal MEMCARD_ReadFile\n"
        "nop\n"
        "j .LMemcardReturnSavedEvent\n"
        "addu $s0,$v0,$zero\n"
        ".LMemcardLoadPart3Or5Check:\n"
        "lw $a0," MC_GP(BUFFER) "\n"
        "lw $a1," MC_GP(FILE_SIZE) "\n"
        "jal MEMCARD_ChecksumLoad\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "beqz $s0,.LMemcardCloseFileReturn\n"
        "addiu $v0,$zero,7\n"
        "beq $s0,$v0,.LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        "lw $v0," MC_GP(STATUS_FLAGS) "\n"
        "nop\n"
        "andi $v0,$v0,0x4\n"
        "bnez $v0,.LMemcardCloseFileReturn\n"
        "nop\n"
        "lw $v1," MC_GP(STAGE) "\n"
        "nop\n"
        "slti $v0,$v1,7\n"
        "beqz $v0,.LMemcardCloseFileReturn\n"
        "addiu $v0,$v1,-3\n"
        "lw $a1," MC_GP(FILE_SIZE) "\n"
        "nop\n"
        "mult $v0,$a1\n"
        "lw $a0," MC_GP(ICON_SIZE) "\n"
        "addiu $v0,$v1,1\n"
        "sw $v0," MC_GP(STAGE) "\n"
        "mflo $a3\n"
        "j .LMemcardReadFileReturn\n"
        "addu $a0,$a0,$a3\n"
        ".LMemcardLoadPart2Or4Read:\n"
        "jal MEMCARD_GetNextSwEvent\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "bnez $s0,.LMemcardLoadReadRetryOrClose\n"
        "addiu $v0,$zero,7\n"
        "lw $v0," MC_GP(STAGE) "\n"
        "lw $v1," MC_GP(STATUS_FLAGS) "\n"
        "sw $zero," MC_GP(CHECKSUM_INDEX) "\n"
        "sw $zero," MC_GP(CHECKSUM_STATUS) "\n"
        "addiu $v0,$v0,1\n"
        "andi $v1,$v1,0x8\n"
        "sw $v0," MC_GP(STAGE) "\n"
        "bnez $v1,.LMemcardLoadPart3Or5Check\n"
        "addiu $s0,$zero,7\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardLoadReadRetryOrClose:\n"
        "beq $s0,$v0,.LMemcardReturnSavedEvent\n"
        "nop\n"
        "lw $v1," MC_GP(RETRIES) "\n"
        "nop\n"
        "blez $v1,.LMemcardCloseFileReturn\n"
        "nop\n"
        "lw $v0," MC_GP(STAGE) "\n"
        "lw $a1," MC_GP(FILE_SIZE) "\n"
        "addiu $v0,$v0,-4\n"
        "mult $v0,$a1\n"
        "lw $a0," MC_GP(ICON_SIZE) "\n"
        "addiu $v0,$v1,-1\n"
        "sw $v0," MC_GP(RETRIES) "\n"
        "mflo $a3\n"
        "j .LMemcardReadFileReturn\n"
        "addu $a0,$a0,$a3\n"
        ".LMemcardSaveParts:\n"
        "jal MEMCARD_GetNextSwEvent\n"
        "nop\n"
        "addu $s0,$v0,$zero\n"
        "bnez $s0,.LMemcardSaveRetryOrClose\n"
        "addiu $v0,$zero,7\n"
        "lw $v1," MC_GP(STAGE) "\n"
        "addiu $v0,$zero,9\n"
        "beq $v1,$v0,.LMemcardSaveWriteNextPart\n"
        "slti $v0,$v1,11\n"
        "beqz $v0,.LMemcardSaveFinish\n"
        "nop\n"
        "lw $v0," MC_GP(STATUS_FLAGS) "\n"
        "nop\n"
        "andi $v0,$v0,0x4\n"
        "bnez $v0,.LMemcardSaveFinish\n"
        "nop\n"
        ".LMemcardSaveWriteNextPart:\n"
        "lw $a2," MC_GP(FILE_SIZE) "\n"
        "addiu $v0,$v1,-9\n"
        "mult $v0,$a2\n"
        "lw $a1," MC_GP(BUFFER) "\n"
        "lw $a0," MC_GP(ICON_SIZE) "\n"
        "addiu $v0,$v1,1\n"
        "sw $v0," MC_GP(STAGE) "\n"
        "j .LMemcardSaveCurrentPartOffset\n"
        "nop\n"
        ".LMemcardSaveFinish:\n"
        "jal MEMCARD_CloseFile\n"
        "nop\n"
        "lw $a0," MC_GP(SLOT) "\n"
        "jal MEMCARD_GetFreeBytes\n"
        "nop\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardSaveRetryOrClose:\n"
        "beq $s0,$v0,.LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        "lw $v0," MC_GP(RETRIES) "\n"
        "nop\n"
        "blez $v0,.LMemcardCloseFileReturn\n"
        "addiu $v0,$v0,-1\n"
        "lw $v1," MC_GP(STAGE) "\n"
        "sw $v0," MC_GP(RETRIES) "\n"
        "addiu $v0,$zero,9\n"
        "bne $v1,$v0,.LMemcardSaveRetryData\n"
        "addiu $v0,$v1,-10\n"
        "addu $a0,$zero,$zero\n"
        "lw $a2," MC_GP(ICON_SIZE) "\n"
        "lui $a1,%hi(data+" MC_STRINGIFY(CTR_MEMCARD_ICON_HAND_DATA_OFFSET) ")\n"
        "j .LMemcardWriteFileReturn\n"
        "addiu $a1,$a1,%lo(data+" MC_STRINGIFY(CTR_MEMCARD_ICON_HAND_DATA_OFFSET) ")\n"
        ".LMemcardSaveRetryData:\n"
        "lw $a2," MC_GP(FILE_SIZE) "\n"
        "nop\n"
        "mult $v0,$a2\n"
        "lw $a1," MC_GP(BUFFER) "\n"
        "lw $a0," MC_GP(ICON_SIZE) "\n"
        ".LMemcardSaveCurrentPartOffset:\n"
        "mflo $a3\n"
        "addu $a0,$a0,$a3\n"
        ".LMemcardWriteFileReturn:\n"
        "jal MEMCARD_WriteFile\n"
        "nop\n"
        "j .LMemcardReturnSavedEvent\n"
        "addu $s0,$v0,$zero\n"
        ".LMemcardCloseFileReturn:\n"
        "jal MEMCARD_CloseFile\n"
        "nop\n"
        ".LMemcardReturnSavedEvent:\n"
        "j .LMemcardReturn\n"
        "addu $v0,$s0,$zero\n"
        ".LMemcardEraseFail:\n"
        "sw $zero," MC_GP(STAGE) "\n"
        "j .LMemcardReturn\n"
        "addiu $v0,$zero,1\n"
        ".LMemcardErasePass:\n"
        "sw $zero," MC_GP(STAGE) "\n"
        "j .LMemcardReturn\n"
        "addu $v0,$zero,$zero\n"
        ".LMemcardDefaultTimeout:\n"
        "addiu $v0,$zero,1\n"
        ".LMemcardReturn:\n"
        "lw $ra,20($sp)\n"
        "lw $s0,16($sp)\n"
        "jr $ra\n"
        "addiu $sp,$sp,24\n"
        ".end MEMCARD_HandleEvent\n"
        ".set\treorder\n"
        ".section .rdata,\"a\",@progbits\n"
        ".align 3\n"
        ".LMemcardHandleEventTable:\n"
        ".word .LMemcardGetInfo\n"
        ".word .LMemcardNewCard\n"
        ".word .LMemcardLoadPart0Start\n"
        ".word .LMemcardLoadPart2Or4Read\n"
        ".word .LMemcardLoadPart3Or5Check\n"
        ".word .LMemcardLoadPart2Or4Read\n"
        ".word .LMemcardLoadPart3Or5Check\n"
        ".word .LMemcardDefaultTimeout\n"
        ".word .LMemcardSaveParts\n"
        ".word .LMemcardSaveParts\n"
        ".word .LMemcardSaveParts\n"
        ".word .LMemcardDefaultTimeout\n"
        ".word .LMemcardEraseFail\n"
        ".word .LMemcardErasePass\n"
        ".text\n");
